# Generated by Django 3.1.7 on 2021-04-14 16:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('length', models.PositiveIntegerField(default=0)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=9, max_digits=10), size=None)),
                ('eye', models.CharField(max_length=1, verbose_name='Глаз')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('sub_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='exam.subexam', verbose_name='Подъисследование')),
            ],
            options={
                'verbose_name': 'Последовательность',
                'verbose_name_plural': 'Последовательности',
                'db_table': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='metric.sequence', verbose_name='Последовательность')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'db_table': 'point',
            },
        ),
    ]
