# Generated by Django 3.1.7 on 2021-04-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clinic', models.CharField(default='', max_length=200, null=True, verbose_name='Клиника, в которой произвели исследование')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='patient.patient', verbose_name='Исследуемый')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'db_table': 'examination',
            },
        ),
        migrations.CreateModel(
            name='SubExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_version', models.CharField(max_length=15, null=True)),
                ('check_type', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_exams', to='exam.examination', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Подъисследование',
                'verbose_name_plural': 'Подъисследование',
                'db_table': 'port',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='exam.examination', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
    ]
