# Generated by Django 3.1.7 on 2021-04-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_diagnosis_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='exam',
        ),
        migrations.DeleteModel(
            name='DiagnosisChoice',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
