# Generated by Django 3.1.7 on 2021-04-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Выбор границы дзн',
                'verbose_name_plural': 'Выбор границы дзн',
            },
        ),
        migrations.CreateModel(
            name='ColorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Выбор цвета дзн',
                'verbose_name_plural': 'Выбор цвета дзн',
            },
        ),
        migrations.CreateModel(
            name='MakulaChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Выбор макулы',
                'verbose_name_plural': 'Выбор макулы',
            },
        ),
        migrations.CreateModel(
            name='PereferyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Выбор периферии',
                'verbose_name_plural': 'Выбор периферии',
            },
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Рекомендации')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomends', to='exam.examination', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
