# Generated by Django 3.1.7 on 2021-04-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[(1, 'Левый'), (2, 'Правый')], max_length=6, verbose_name='Тип глаза')),
                ('sight_sharpness', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Острота зрения')),
                ('makula', models.CharField(choices=[], default='', max_length=100, verbose_name='Макула')),
                ('periphery', models.CharField(choices=[], default='', max_length=100, verbose_name='Переферия')),
                ('sight_area', models.CharField(default='default', max_length=100, verbose_name='Поле зрения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyes_info', to='exam.examination', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Информация о глазе',
                'verbose_name_plural': 'Информация о глазах',
                'unique_together': {('side', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='DZN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[], default='', max_length=100, verbose_name='Цвет')),
                ('border', models.CharField(choices=[], default='', max_length=100, verbose_name='Границы')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dzn', to='info.eyeinfo', verbose_name='Информация о глазе')),
            ],
            options={
                'verbose_name': 'Диск зрительного нерва',
                'verbose_name_plural': 'Диски зрительных нервов',
            },
        ),
    ]
