# Generated by Django 3.1.7 on 2021-04-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_eyeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DZN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[], default='', max_length=100, verbose_name='Цвет')),
                ('border', models.CharField(choices=[], default='', max_length=100, verbose_name='Границы')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dzn', to='info.eyeinfo', verbose_name='Информация о глазе')),
            ],
            options={
                'verbose_name': 'Диск зрительного нерва',
                'verbose_name_plural': 'Диски зрительных нервов',
            },
        ),
    ]
