# Generated by Django 3.1.7 on 2021-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20210414_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.TextField(default='', max_length=100, verbose_name='Название диагноза'),
        ),
        migrations.AlterField(
            model_name='dzn',
            name='border',
            field=models.CharField(default='', max_length=100, verbose_name='Границы'),
        ),
        migrations.AlterField(
            model_name='dzn',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='eyeinfo',
            name='makula',
            field=models.CharField(default='', max_length=100, verbose_name='Макула'),
        ),
        migrations.AlterField(
            model_name='eyeinfo',
            name='periphery',
            field=models.CharField(default='', max_length=100, verbose_name='Переферия'),
        ),
        migrations.AlterField(
            model_name='eyeinfo',
            name='side',
            field=models.CharField(max_length=6, verbose_name='Тип глаза'),
        ),
    ]
