# Generated by Django 3.1.7 on 2021-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210414_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PereferyChoice',
            new_name='PeripheryChoice',
        ),
        migrations.AlterField(
            model_name='eyeinfo',
            name='periphery',
            field=models.CharField(default='', max_length=100, verbose_name='Периферия'),
        ),
    ]
