# Generated by Django 3.1.7 on 2021-04-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_diagnosis_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='side',
        ),
    ]
